name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ["17", "16", "14", "12"]

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm config set enable-pre-post-scripts true
          pnpm i --frozen-lockfile
        env:
          CI: true

      - name: Test
        run: pnpm t
        env:
          CI: true
