name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ["12", "10"]

    steps:
      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
        env:
          HUSKY_SKIP_INSTALL: 1

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Test
        run: yarn test
        env:
          CI: true
